# Generated by Django 2.2.5 on 2019-10-06 15:41

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of the last update')),
                ('provider_id', models.CharField(max_length=64, verbose_name='provider id')),
                ('names', models.CharField(max_length=64, verbose_name='names')),
                ('surnames', models.CharField(max_length=64, verbose_name='surnames')),
                ('birthday', models.CharField(blank=True, max_length=32, null=True, verbose_name='birthday')),
                ('gender', models.CharField(blank=True, max_length=8, null=True, verbose_name='gender')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='phone')),
                ('email', models.EmailField(max_length=128, verbose_name='email')),
                ('picture', models.CharField(max_length=256, verbose_name='picture')),
                ('location', models.CharField(blank=True, max_length=64, null=True, verbose_name='locación')),
                ('category', models.CharField(blank=True, max_length=16, null=True, verbose_name='category')),
                ('skill', models.CharField(blank=True, max_length=16, null=True, verbose_name='skill')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('last_login', models.DateTimeField(verbose_name='last login')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of the last update')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 128 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=128, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(max_length=128, verbose_name='email')),
                ('names', models.CharField(max_length=64, verbose_name='names')),
                ('surnames', models.CharField(max_length=64, verbose_name='surnames')),
                ('phone', models.CharField(max_length=22, verbose_name='phone')),
                ('gender', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], max_length=9, verbose_name='gender')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
